export const templates = {
	minimal: [
		{
			id: 1,
			title: "font-bold text-4xl text-balance text-black",
			description: "font-medium text-lg text-black",
			author: "font-semibold text-xl text-black",
			url: "text-center italic text-black underline",
			svg: "size-7 absolute top-4 right-5 !invert",
			background: "bg-[#f89b29]",
		},
		{
			id: 2,
			title: "font-extrabold text-5xl text-balance text-gray-800",
			description: "font-normal text-lg text-gray-600",
			author: "font-semibold text-xl text-gray-500",
			url: "text-center italic text-gray-700",
			svg: "size-6 absolute bottom-4 left-5",
			background: "bg-white",
		},
		{
			id: 3,
			title: "font-bold text-3xl text-balance text-gray-900",
			description: "font-light text-md text-gray-700",
			author: "font-semibold text-lg text-gray-600",
			url: "text-center italic text-gray-800",
			svg: "size-8 absolute top-6 left-6",
			background: "bg-gray-200",
		},
	],
	gradients: [
		{
			id: 1,
			title: "font-bold text-4xl text-balance text-white",
			description: "font-medium text-lg text-white/90",
			author: "font-semibold text-xl text-white/80",
			url: "text-center italic text-white underline",
			svg: "size-7 absolute top-4 left-4",
			background: "bg-[url('/assets/1.jpg')] bg-cover bg-top",
		},
		{
			id: 2,
			title: "font-extrabold text-5xl text-balance text-gray-50",
			description: "font-normal text-lg text-gray-200",
			author: "font-semibold text-xl text-gray-300",
			url: "text-center italic text-gray-100",
			svg: "size-6 absolute bottom-4 right-4",
			background: "bg-[url('/assets/2.jpg')] bg-cover bg-top",
		},
		{
			id: 3,
			title: "font-bold text-3xl text-balance text-white",
			description: "font-light text-md text-white/75",
			author: "font-semibold text-lg text-white/70",
			url: "text-center italic text-white",
			svg: "size-8 absolute top-6 right-6",
			background: "bg-[url('/assets/3.jpg')] bg-cover bg-top",
		},
	],
	colorful: [
		{
			id: 1,
			title: "font-bold text-4xl text-balance text-purple-800",
			description: "font-medium text-lg text-pink-600",
			author: "font-semibold text-xl text-yellow-500",
			url: "text-center italic text-teal-500 underline",
			svg: "size-7 absolute top-4 right-4",
			background: "bg-gradient-to-r from-purple-400 via-pink-500 to-red-500",
		},
		{
			id: 2,
			title: "font-extrabold text-5xl text-balance text-blue-800",
			description: "font-normal text-lg text-blue-600",
			author: "font-semibold text-xl text-cyan-500",
			url: "text-center italic text-indigo-500",
			svg: "size-6 absolute bottom-4 left-4",
			background: "bg-gradient-to-b from-blue-400 to-cyan-500",
		},
		{
			id: 3,
			title: "font-bold text-3xl text-balance text-green-800",
			description: "font-light text-md text-green-600",
			author: "font-semibold text-lg text-lime-500",
			url: "text-center italic text-yellow-400",
			svg: "size-8 absolute top-6 left-6",
			background: "bg-gradient-to-l from-green-400 via-yellow-300 to-lime-500",
		},
	],
	typographic: [
		{
			id: 1,
			title: "font-serif font-bold text-5xl text-center text-gray-900",
			description: "font-serif font-light text-xl text-gray-700",
			author: "font-mono font-medium text-lg text-gray-600",
			url: "text-center font-serif italic text-gray-800",
			svg: "size-7 absolute top-4 right-4",
			background: "bg-white",
		},
		{
			id: 2,
			title: "font-sans font-bold text-4xl text-left text-gray-900",
			description: "font-sans font-light text-lg text-gray-700",
			author: "font-mono font-medium text-md text-gray-600",
			url: "text-left font-sans italic text-gray-800",
			svg: "size-6 absolute bottom-4 left-4",
			background: "bg-gray-50",
		},
		{
			id: 3,
			title: "font-serif font-extrabold text-6xl text-right text-gray-900",
			description: "font-serif font-thin text-md text-gray-600",
			author: "font-mono font-semibold text-lg text-gray-500",
			url: "text-right font-serif italic text-gray-700",
			svg: "size-8 absolute top-6 left-6",
			background: "bg-gray-100",
		},
	],
};
